version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"

  web:
    build: .
    command: ["sh", "-c", "sleep 2 && python db_setup.py && flask run --host=0.0.0.0 --port=8100"]
    environment:
      FLASK_APP: server
      FLASK_ENV: development
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8100:8100"
